### ISSUE TITLE
goftests 0.2.4 on PyPI does not have LICENSE.txt file

### ISSUE THREAD

**Issue by jfinkels** [posterior/goftests#16]
See my comments on issue #13. This is causing `pip install goftests` to fail.

**Comment by danring** [comment]
This should be fixed, but please do verify.

LICENSE.txt file is now preserved in both the wheel and the source tarfile, and `pip install goftests` succeeds.

**Comment by jfinkels** [comment]
This is fixed with goftests 0.2.5.
