### ISSUE TITLE
goftests is not available via the conda package manager

### ISSUE THREAD

**Issue by jfinkels** [posterior/goftests#5]
I don't have much experience with conda, but goftests seems to be unavailable to `conda install` through the default repositories. I guess it needs to be uploaded to Continuum's repository in some way.

**Comment by fritzo** [comment]
@jfinkels Do you want to own the conda package? I'm not working on this package anymore, but I could add you to the posterior org if you want.

**Comment by jfinkels** [comment]
Umm let me think about it. I don't use conda so it seems silly to put me in charge of it haha. I only ask for my colleagues who use it. Let me discuss it with them.

**Comment by jfinkels** [comment]
Thanks to @danring, version 0.2.3 seems to live in conda-forge, a community-driven conda package repository, now: https://conda-forge.github.io/feedstocks. (Not sure how to update the version there.)

Might be nice to add instructions on how to install from that repository before closing this issue.

**Comment by danring** [comment]
Version 0.2.5 is also now available via conda-forge.

Assuming you have a working conda environment, you can install goftests (from the conda-forge "channel") with:
```
conda install -c conda-forge goftests
```
