### ISSUE TITLE
Replace scikit-learn's nearest neighbors with scipy's

### ISSUE THREAD

**Issue by jfinkels** [posterior/goftests#6]
Scikit-learn is a large dependency compared to its single use in goftests, in the [`get_nearest_neighbor_distances` function](https://github.com/posterior/goftests/blob/master/goftests/__init__.py#L198). Perhaps it could be replaced with [SciPy's KDTree](http://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.html#scipy.spatial.KDTree) (or cKDTree), since SciPy is already required.

**Comment by jfinkels** [comment]
cc @mattbarr

**Comment by fritzo** [comment]
Sounds reasonable to me. I didn't know about SciPy's KDTree.

**Comment by jfinkels** [comment]
This was fixed by pull request #9.
